#!/usr/local/bin/python3.5

# Banktivity 6 Data Query v1
# Extract Banktivity Transactions (including Securities) and save to CSV file 
# by Mark Jochems, mjochems@pr2m.com
# 26 Mar 2017

# import modules
import csv, sys
import sqlite3

from glob import glob; from os.path import expanduser
conn = sqlite3.connect( # open Lr sqlite database for current user
    glob(expanduser('~/Dropbox/Apps/Banktivity/Data/mjochems.bank6/StoreContent/core.sql'))[0])

cursor = conn.cursor()

# SQL Query
SQL = """
SELECT
strftime('%d/%m/%Y', datetime(ZTRANSACTION.ZPDATE+978307200, 'unixepoch', 'localtime')) AS DATE,
CASE
WHEN ZACCOUNT.ZFINANCIALACCOUNT = 1 
THEN ZTRANSACTIONTYPE.ZPNAME 
ELSE '-split-' 
END AS TYPE,
ZTRANSACTION.ZPCHECKNUMBER AS REF,
ZACCOUNT.ZPNAME AS ACCOUNT,
ZTRANSACTION.ZPTITLE AS PAYEE,
CASE
WHEN ZLINEITEM.ZPMEMO IS NULL
THEN ZTRANSACTION.ZPNOTE
ELSE ZLINEITEM.ZPMEMO
END AS DETAILS,
group_concat(ZTAG.ZPNAME, ", ") AS TAGS,
ZCURRENCY.ZPCODE AS CCY,
ZSECURITYLINEITEM.ZPSHARES AS SHARES,
CASE 
WHEN ZLINEITEM.ZPTRANSACTIONAMOUNT = 0 AND ZSECURITYLINEITEM.ZPAMOUNT NOT NULL 
THEN ZSECURITYLINEITEM.ZPAMOUNT
ELSE ZLINEITEM.ZPTRANSACTIONAMOUNT
END AS AMOUNT,
CASE
WHEN ZCURRENCY.ZPCODE IS "ZAR"
THEN 1 / ZLINEITEM.ZPEXCHANGERATE
ELSE ZLINEITEM.ZPEXCHANGERATE
END AS EXCH_RATE,
ZSECURITY.ZPNAME AS SECURITY,
ZSECURITYLINEITEM.ZPCOMMISSION AS COMM,
ZSECURITYLINEITEM.ZPINCOME AS INCOME,
ZSECURITYLINEITEM.ZPPRICEPERSHARE AS PRICE,
ZTRANSACTION.Z_PK AS TRN_NO,
ZLINEITEM.Z_PK AS LINE_NO,
ZLINEITEMSOURCE.Z_PK AS SOURCE_NO,
ZTRANSACTION.ZPFILEATTACHMENT AS FILE_NO,
ZACCOUNT.ZFINANCIALACCOUNT AS FIN_ACC,
ZLINEITEMSOURCE.ZPDETAILS AS SOURCE_INFO,
ZLINEITEMSOURCE.ZPSOURCETYPE AS SOURCE,
strftime('%d/%m/%Y %H:%M:%S', datetime(ZTRANSACTION.ZPCREATIONTIME+978307200, 'unixepoch', 'localtime')) AS CREATED,
strftime('%d/%m/%Y %H:%M:%S', datetime(ZTRANSACTION.ZPMODIFICATIONDATE+978307200, 'unixepoch', 'localtime')) AS MODIFIED
FROM
ZTRANSACTION
JOIN ZCURRENCY
ON ZTRANSACTION.ZPCURRENCY = ZCURRENCY.Z_PK 
JOIN ZTRANSACTIONTYPE
ON ZTRANSACTION.ZPTRANSACTIONTYPE = ZTRANSACTIONTYPE.Z_PK 
JOIN ZLINEITEM
ON ZLINEITEM.ZPTRANSACTION = ZTRANSACTION.Z_PK 
LEFT JOIN ZACCOUNT
ON ZLINEITEM.ZPACCOUNT = ZACCOUNT.Z_PK 
LEFT JOIN ZSECURITYLINEITEM
ON ZSECURITYLINEITEM.ZPLINEITEM = ZLINEITEM.Z_PK 
LEFT JOIN ZSECURITY
ON ZSECURITYLINEITEM.ZPSECURITY = ZSECURITY.Z_PK 
LEFT JOIN ZLINEITEMSOURCE
ON ZLINEITEMSOURCE.ZPLINEITEM = ZLINEITEM.Z_PK 
LEFT JOIN Z_17PTAGS
ON ZLINEITEM.Z_PK = Z_17PTAGS.Z_17PLINEITEMS 
LEFT JOIN ZTAG
ON Z_17PTAGS.Z_50PTAGS = ZTAG.Z_PK
GROUP BY
ZLINEITEM.Z_PK
ORDER BY
ZTRANSACTION.ZPDATE DESC
"""

# Execute query
cursor.execute(SQL)

# Write data to CSV file 
with open(expanduser("~/Desktop/Banktivity Transactions.csv"), "w") as csv_file:
    csv_writer = csv.writer(csv_file)
    csv_writer.writerow([i[0] for i in cursor.description]) # write headers
    csv_writer.writerows(cursor)

print ("Banktivity Data saved to File", csv_file)